replicaCount: 1
appName: mysql

nameSpace: gitbucket

image:
  repository: mysql
  pullPolicy: IfNotPresent
  tag: latest

mysqlDatabase: gitbucket
mysqlRootPassword:
mysqlUser:
mysqlPassword:

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
