plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
keyed_groups:
  - prefix: '' # No prefix added to the group name
    key: tags['Environment'] # Assuming both instances have an 'Environment' tag
    separator: "" # No separator between prefix and key value
compose:
  ansible_host: public_ip_address
