plugin: amazon.aws.aws_ec2
regions:
  - eu-central-1
keyed_groups:
  - prefix: ''
    key: tags['Environment'] 
    separator: "" 
compose:
  ansible_host: public_ip_address
host_vars:
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
