apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-db-script
data:
  init-db.sh: |
    #! /bin/bash
    set -e

    mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
        CREATE DATABASE IF NOT EXISTS gitbucket;
        CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY 'password';
        GRANT ALL PRIVILEGES ON gitbucket.* TO '${MYSQL_USER}'@'%';
        ALTER USER '${MYSQL_USER}'@'%' IDENTIFIED WITH mysql_native_password BY '${MYSQL_PASSWORD}';
        FLUSH PRIVILEGES;
    EOSQL