apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secret"
  namespace: {{ .Values.nameSpace }}
type: Opaque
stringData:
  mysql-user: {{ .Values.mysqlUser }}
  mysql-password: {{ .Values.mysqlPassword }}
  mysql-root-password: {{ .Values.mysqlRootPassword }}