apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-service"
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001