apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec: 
      containers:
      - name: gitbucket
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        envFrom:
        resources:
          requests:
            memory: "500Mi" 
            cpu: "500m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "1500Mi"
            cpu: "1000m"