apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec: 
      containers:
      - name: gitbucket
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
#        volumeMounts: 
#        - name: gitbucket-cm
#          mountPath: /gitbucket
#      volumes:
#      - name: gitbucket-cm
#        configMap:
#          name: gitbucket-configmap   
#          items:
#          - key: database.conf
#            path: database.conf 
        envFrom:
        resources:
          requests:
            memory: {{ .Values.memoryRequest }}
            cpu: {{ .Values.cpuRequest }}
          limits:
            memory: {{ .Values.memoryLimit }}
            cpu: {{ .Values.cpuLimit }}