apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secret"
  namespace: {{ .Values.nameSpace }}
type: Opaque
stringData:
  user: {{ .Values.user }}
  password: {{ .Values.password }}