---
- name: Setup SSH Key and Aggregate Hosts
  hosts: tag_Name_blue
  gather_facts: no
  vars:
    ansible_user: ec2-user 
    ansible_ssh_private_key_file: ./id_rsa
  tasks:
    - name: Add all hosts to ec2_instances group
      add_host:
        name: "{{ inventory_hostname }}"
        groups: ec2_instances
        ansible_ssh_private_key_file: ./id_rsa
        ansible_user: ec2-user

- name: Deploy Gitbucket Application to EC2
  hosts: blue
  become: true
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ./id_rsa
  roles:
  - gitbucket-deploy
