apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitbucket-ingress
  namespace: gitbucket
spec:
  tls:
  - hosts:
      - https-example.foo.com
    secretName: testsecret-tls
  rules:
  - host: gitbucket-project.com
    http:
      paths:
      - backend:
          service:
            name: "{{ .Values.appName }}-service"
            port:
              number: 8080